### ISSUE TITLE
Create session and cookie with LUA

### ISSUE THREAD

**Issue by batuhangoksu** [lpereira/lwan#110]
We are developing a LUA application with LWAN. In our development procedure we wanted to form SESSION and COOKIE on LWAN but unfortunately we realized that we are unable to do so. We propose you to enable the SESSION and COOKIE related development on LWAN.

**Comment by lpereira** [comment]
Support has been added on ea4cade. Please test and report if it works for you.

**Comment by lpereira** [comment]
As of a4dd4ccd5, it's possible to set the headers from Lua. Not the best API to set cookies yet, but it's now possible.
