### ISSUE TITLE
C handler with embed lua

### ISSUE THREAD

**Issue by whatvn** [lpereira/lwan#112]
Hello, 

We've already implement lwan to meet our internal requirement and it's working good so far. 
Most of our work is writing some http server which interacts with various back end, for example Apache thrift. 

Thrift doesn't provide a good client for C, for C++ is ok but I don't want to write C++ and we're lack of experience with C++. So, is it possible by now that we write lwan handler in C, but at some point (connect to thrift backend), call lua code to execute and build response for C handler? 

Thanks,

**Comment by lpereira** [comment]
I'd write the client in C and then expose it to LuaJIT via ffi. It's going to be a lot easier.

However, keep in mind that integrating with Lwan's I/O loops is going to be tricky, as they can only handle activity in the connection file descriptor. This will eventually be fixed but there's no estimate when it's going to happen.

**Comment by lpereira** [comment]
Closing the issue as that's pretty old; feel free to reopen or open another one.
