### ISSUE TITLE
epoll is not available on mac

### ISSUE THREAD

**Issue by tkisme** [lpereira/lwan#116]
epoll() does not exist on Mac OS X. It does have the somewhat-similar kqueue system call. Alternatively, you can use a library such as libevent that abstracts away the difference.
So,is there anything I can do on Mac?

**Comment by lpereira** [comment]
Not at the moment. There's the issue #24, however, where I suggest creating an `epoll()`-like interface on top of `kqueue()`.

**Comment by lpereira** [comment]
Got Lwan working on FreeBSD (I don't have a Mac to test, but given that both have `kqueue`, it should work). The port is quite hackish at the moment, some things are not working. I can push it to another branch if you're willing to test.

**Comment by fiorix** [comment]
I can help with building and basic testing on OS X.

**Comment by lpereira** [comment]
Great, thanks! Just pushed the `bsd-hack` branch. If you manage to compile it on OS X, it'll not be able to reply to any request (only give out 404s or 500s).

**Comment by fiorix** [comment]
Bad options to clang:

    $ make
    Scanning dependencies of target generate_mime_types_table
    [  3%] Generating ../mime-types.h
    [  3%] Built target generate_mime_types_table
    Scanning dependencies of target lwan-common
    [  6%] Building C object common/CMakeFiles/lwan-common.dir/epoll-bsd.c.o
    clang: error: unsupported argument 'undefined' to option 'fsanitize='
    make[2]: *** [common/CMakeFiles/lwan-common.dir/epoll-bsd.c.o] Error 1
    make[1]: *** [common/CMakeFiles/lwan-common.dir/all] Error 2

Have to step away for now but will come back to this later today.

**Comment by lpereira** [comment]
Ah, yes. Use `cmake -DASAN=OFF -DUBSAN=OFF`.

**Comment by tkisme** [comment]
still have error on mac
```
$ make
Scanning dependencies of target generate_mime_types_table
[  2%] Generating ../mime-types.h
[  2%] Built target generate_mime_types_table
Scanning dependencies of target lwan-common
[  5%] Building C object common/CMakeFiles/lwan-common.dir/epoll-bsd.c.o
[  7%] Building C object common/CMakeFiles/lwan-common.dir/base64.c.o
[ 10%] Building C object common/CMakeFiles/lwan-common.dir/hash.c.o
[ 12%] Building C object common/CMakeFiles/lwan-common.dir/int-to-str.c.o
[ 15%] Building C object common/CMakeFiles/lwan-common.dir/list.c.o
[ 17%] Building C object common/CMakeFiles/lwan-common.dir/lwan.c.o
/Users/tk/MEGAsync/cloud/libs/lwan/common/lwan.c:204:32: warning: missing field 'data' initializer
      [-Wmissing-field-initializers]
    lwan_url_map_t url_map = {0};
                               ^
/Users/tk/MEGAsync/cloud/libs/lwan/common/lwan.c:208:27: warning: missing field 'path' initializer
      [-Wmissing-field-initializers]
    config_t isolated = {0};
                          ^
/Users/tk/MEGAsync/cloud/libs/lwan/common/lwan.c:636:25: warning: implicit declaration of function 'accept4' is invalid in C99
      [-Wimplicit-function-declaration]
        int client_fd = accept4(main_socket, NULL, NULL, SOCK_NONBLOCK | SOCK_CLOEXEC);
                        ^
/Users/tk/MEGAsync/cloud/libs/lwan/common/lwan.c:636:58: error: use of undeclared identifier 'SOCK_NONBLOCK'
        int client_fd = accept4(main_socket, NULL, NULL, SOCK_NONBLOCK | SOCK_CLOEXEC);
                                                         ^
/Users/tk/MEGAsync/cloud/libs/lwan/common/lwan.c:636:74: error: use of undeclared identifier 'SOCK_CLOEXEC'
        int client_fd = accept4(main_socket, NULL, NULL, SOCK_NONBLOCK | SOCK_CLOEXEC);
                                                                         ^
3 warnings and 2 errors generated.
make[2]: *** [common/CMakeFiles/lwan-common.dir/lwan.c.o] Error 1
make[1]: *** [common/CMakeFiles/lwan-common.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by lpereira** [comment]
@tkisme Could you please try removing the `| SOCK_CLOEXEC` from the offending line (`common/lwan.c`, line 636), and see if the build progresses?

**Comment by tkisme** [comment]
@lpereira 
still got error
```
$ make
[  2%] Built target generate_mime_types_table
Scanning dependencies of target lwan-common
[  5%] Building C object common/CMakeFiles/lwan-common.dir/lwan.c.o
/Users/tk/MEGAsync/cloud/libs/lwan/common/lwan.c:204:32: warning: missing field 'data' initializer
      [-Wmissing-field-initializers]
    lwan_url_map_t url_map = {0};
                               ^
/Users/tk/MEGAsync/cloud/libs/lwan/common/lwan.c:208:27: warning: missing field 'path' initializer
      [-Wmissing-field-initializers]
    config_t isolated = {0};
                          ^
/Users/tk/MEGAsync/cloud/libs/lwan/common/lwan.c:636:25: warning: implicit declaration of function 'accept4' is invalid in C99
      [-Wimplicit-function-declaration]
        int client_fd = accept4(main_socket, NULL, NULL, SOCK_NONBLOCK );
                        ^
/Users/tk/MEGAsync/cloud/libs/lwan/common/lwan.c:636:58: error: use of undeclared identifier 'SOCK_NONBLOCK'
        int client_fd = accept4(main_socket, NULL, NULL, SOCK_NONBLOCK );
                                                         ^
3 warnings and 1 error generated.
make[2]: *** [common/CMakeFiles/lwan-common.dir/lwan.c.o] Error 1
make[1]: *** [common/CMakeFiles/lwan-common.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by lpereira** [comment]
Any luck with this? I know Lwan builds on FreeBSD now, although it doesn't work (it crashes right after servicing the first request). I'm not experienced with FreeBSD so it's taking more time than I care to admit to get this up and running. With FreeBSD support at least building, it should be easier to get an OS X running as well, although I'm not sure if it's going to crash the same way as the FreeBSD version or not.

**Comment by lpereira** [comment]
It seems that Lwan is now working on OS X as well. Closing the issue.
