### ISSUE TITLE
PROXY protocol

### ISSUE THREAD

**Issue by malthe** [lpereira/lwan#117]
The [Hitch TLS proxy](https://hitch-tls.org/) speaks through the simple [PROXY protocol](http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt) to a backend server, e.g.

    PROXY TCP4 192.168.0.1 192.168.0.11 56324 443\r\n
    GET / HTTP/1.1\r\n
    Host: 192.168.0.11\r\n
    \r\n

Supporting this protocol makes #12 less important, perhaps obviating it entirely.

**Comment by lpereira** [comment]
This issue can now be closed.
