### ISSUE TITLE
Support for TLS sockets

### ISSUE THREAD

**Issue by lpereira** [lpereira/lwan#12]

**Comment by kayrus** [comment]
+1 for TLS support in listening sockets.

**Comment by lpereira** [comment]
Another thing that would benefit from TLS sockets is #17 (HTTP/2.0).

**Comment by hdante** [comment]
Any updates about this ?

**Comment by lpereira** [comment]
No updates, @hdante.  I did play with BearSSL some months ago but never made it work with Lwan.  I'm sort of waiting for it to support kTLS.

**Comment by lpereira** [comment]
Implemented!
