### ISSUE TITLE
parse_query_string issue

### ISSUE THREAD

**Issue by ancuop** [lpereira/lwan#122]
Hi Ipereira, 
I have an issue on function get_query_string, could you help to fix it?
Problem: 
when i call a request example: 
      http://127.0.0.1:8080/report?fa&g0=71&auth=23423
lwan parse the request as: key1="fa&g0", value1="71", key2="auth", value2="23423"
It should be: key1="fa", value1=NULL, key2="g0", value2=71, .... 
Thanks,

**Comment by lpereira** [comment]
Any reason in this example `fa` does not have a value?

**Comment by ancuop** [comment]
Sorry for unclear question. I mean it should be g0 = 71 instead of fa&g0 = 71
Thanks,

**Comment by lpereira** [comment]
I understand that, but why there's no `=` after `fa`?

**Comment by trietnm2** [comment]
I think in some case, user pass wrong format of  parameters. Maybe Lwan shoud split key-value by '&' at first. In this case, 'fa' param could be ignore.

**Comment by whatvn** [comment]
query string value is not required in rfc, see: http://tools.ietf.org/html/rfc3986#section-3.4 
As we *often* use key=value in query string, so we assume that a query string must follow key=value schema but what we're assuming is wrong :)

**Comment by lpereira** [comment]
Although the `application/x-www-form-urlencoded` encoding algorithm as published by W3C does indeed specify for the `=` character to be added after the key, the decoding algorithm states that, if no `=` is found, the value should be the considered to be an empty string. [See here](http://www.w3.org/TR/html/forms.html#application/x-www-form-urlencoded-decoding-algorithm).

In other words: both your client and Lwan are not conforming to the specification. Your client should always send the `=`, and Lwan should be lenient and consider the value to be an empty string in this case.
