### ISSUE TITLE
Build fails on Ubuntu 12.04

### ISSUE THREAD

**Issue by JujuLand** [lpereira/lwan#135]
Here are the cmake returns :

alain@Gramps-JujuLand:/opt/TuxPrograms/trunks/lwan/build$ cmake .. -DCMAKE_BUILD_TYPE=Release
-- No clock_gettime() in libc. Linking with -lrt.
-- jemalloc and tcmalloc were not found, using system malloc
-- Valgrind headers not found -- disabling valgrind support
-- Building with Lua support using lua5.1
-- Found MySQL includes at /usr/include/mysql
-- Found MySQL client library at /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/TuxPrograms/trunks/lwan/build

Here are the make returns:

alain@Gramps-JujuLand:/opt/TuxPrograms/trunks/lwan/build$ make
[  2%] Built target generate_mime_types_table
[  5%] Building C object common/CMakeFiles/lwan-common.dir/base64.c.o
cc1: erreur: unrecognised command line option ‘-std=gnu11’
make[2]: *** [common/CMakeFiles/lwan-common.dir/base64.c.o] Erreur 1
make[1]: *** [common/CMakeFiles/lwan-common.dir/all] Erreur 2
make: *** [all] Erreur 2

Thanks
A+

**Comment by lpereira** [comment]
Ubuntu 12 is too old. The compiler that comes with it isn't supported.
