### ISSUE TITLE
How to handle content types other than application/x-www-form-urlencoded?

### ISSUE THREAD

**Issue by matt-42** [lpereira/lwan#136]
Hi,

I'd like to send post params via the application/json content type. But it seems like lwan only handles urlencoded post data: https://github.com/lpereira/lwan/blob/master/common/lwan-request.c#L424

Is it possible to get direct access to the request body to manually parse the POST json object?
Also, it would be nice to have access to the content type header.

**Comment by lpereira** [comment]
Coincidentally, another user asked the very same thing on IRC yesterday. It's simple to implement, just have to carve some time for it.

**Comment by lpereira** [comment]
As of now, it's possible to have access to the request body (request->post_data.value and request->post_data.len), not the Content-Type, which is currently private. Lwan won't mess with the request body if it's not the type it expects, so in the mean time you can parse it yourself if you know you're expecting JSON (or anything else). I'll cook up a patch to expose the Content-Type.
