### ISSUE TITLE
Shared Library

### ISSUE THREAD

**Issue by HalosGhost** [lpereira/lwan#138]
It would be great if liblwan-common could be built as a shared library instead of a dynamic library. It would make life a lot simpler for creating arbitrary servers/sites (since the headers and library could distributed and ``#include`` and ``-l`` is all that would be necessary).

**Comment by lpereira** [comment]
I'm working on having `pkg-config` support, which will help having shared libraries, and finding the installed Lwan (and its dependencies, linking flags, etc) easier.

**Comment by HalosGhost** [comment]
closed via #148

**Comment by HalosGhost** [comment]
I have tentatively packaged ``liblwan`` for [Arch Linux](https://aur.archlinux.org/packages/liblwan-git/) in case you are interested.

**Comment by lpereira** [comment]
There's an [AUR package](https://aur.archlinux.org/packages/lwan-git/) already; you might want to coordinate with the author, as it hasn't been updated since 2015.

**Comment by HalosGhost** [comment]
I did see that, but since the install rule at the moment does not install the command-line tool ``lwan``, I figured it would make sense to leave them as two separate packages. However, merging them (à la curl) is fine with me.

Can you update the ``install`` rule to install the command, and I will request that the packages be merged.

**Comment by lpereira** [comment]
Sure, I'll do that.
