### ISSUE TITLE
Can't compiled with FD_NONBLOCK error

### ISSUE THREAD

**Issue by hnkien** [lpereira/lwan#142]
I got this error when compile the project:

missing.c: In function ‘accept4’:
missing.c:94:20: error: ‘FD_NONBLOCK’ undeclared (first use in this function)
        newflags |= FD_NONBLOCK;

I don't know what is from the constant FD_NONBLOCK. My server is Centos 7.
Any advice? Thank you very much!

**Comment by lpereira** [comment]
It was my mistake. Could you please try updating the source and building again?

(I find it weird that accept4() isn't available in CentOS 7, though. It's not a recent system call.)

**Comment by hnkien** [comment]
Confirmed error fixed. 
Thank you very much!
