### ISSUE TITLE
HTTPS support?

### ISSUE THREAD

**Issue by hnkien** [lpereira/lwan#144]
Do you have plan to support HTTPS protocol?
Thank you very much!

**Comment by lpereira** [comment]
Thanks for reporting the issue! Yes, HTTPS is planned. Currently, there's no way to have HTTPS in Lwan without a terminator proxy; luckily, it supports the PROXY protocol, so you can use something like Hitch.

This is a duplicate of #12. I'm closing this issue; if you have further comments, please comment in issue #12 instead.
