### ISSUE TITLE
Undefined behavior sanitizer fails Debug build with GCC 4.8.x

### ISSUE THREAD

**Issue by fischermario** [lpereira/lwan#147]
I tried to build the latest lwan under Ubuntu 14.04 (gcc 4.8.4) with

`cmake .. -DCMAKE_BUILD_TYPE=Debug`

and got this after starting make:

>Scanning dependencies of target mimegen
[  2%] Building C object common/CMakeFiles/mimegen.dir/__/tools/mimegen.c.o
cc: error: unrecognized command line option ‘-fsanitize=undefined’
make[2]: *** [common/CMakeFiles/mimegen.dir/__/tools/mimegen.c.o] Error 1
make[1]: *** [common/CMakeFiles/mimegen.dir/all] Error 2
make: *** [all] Error 2

The reason for this error is the GCC version. I found out that you need
- GCC >= 4.8 for the address sanitizer
- GCC >= 4.9 for the undefined behavior sanitizer

I have attached a patch to correct the behavior of cmake and to make the right decision:
[lwan_sanitizer_20160520.patch.txt](https://github.com/lpereira/lwan/files/289692/lwan_sanitizer_20160520.patch.txt)

In the long run I would recommend to stick to a tested solution like:
https://github.com/arsenm/sanitizers-cmake

**Comment by lpereira** [comment]
Applied the patch, thank you! I've starred the `sanitizers-cmake` repository, so that I can eventually use it.
