### ISSUE TITLE
Multiple listeners support

### ISSUE THREAD

**Issue by lpereira** [lpereira/lwan#15]

**Comment by HalosGhost** [comment]
I think my favorite part of this is that it might allow for the possibility of having the same server handle both HTTPS and HTTP (just having the ``80`` listener forcibly redirect to the https address).

**Comment by fiorix** [comment]
Well, not only that. You can use the NextProto field to serve any SSL/TLS connection from the same port. In Go we use it to serve HTTPS and gRPC on the same port for example.

**Comment by lpereira** [comment]
Lwan kinda supports multiple listeners now (HTTP and HTTPS). Closing this issue.
