### ISSUE TITLE
--config option

### ISSUE THREAD

**Issue by HalosGhost** [lpereira/lwan#152]
``lwan`` has a ``--config`` option (or, at least, the ``--help`` output suggests there is one):

```console
$ lwan --help
Usage: lwan [--root /path/to/root/dir] [--listener addr:port]
        [--config]
Serve files through HTTP.

Defaults to listening on *:8080, serving from ./wwwroot.

Options:
        -r, --root      Path to serve files from (default: ./wwwroot).
        -l, --listener  Listener (default: *:8080).
        -h, --help      This.

Examples:
  Serve system-wide documentation: lwan -r /usr/share/doc
        Serve on a different port: lwan -l '*:1337'

Report bugs at <https://github.com/lpereira/lwan>.
```

But when running ``lwan`` using that option, an error is thrown:

```console
$ lwan --config $HOME/.config/lwan/lwan.conf
lwan: unrecognized option '--config'
Run lwan --help for usage information.
```

If the config option is no longer valid (or is not yet available to be used), it should probably be removed from the usage line.

If it should be functional and this is a bug, then the options list in the help output should probably include it and runtime should respect it as a passed option.

**Comment by lpereira** [comment]
It's indeed a bug. I'll implement this soon(ish).
