### ISSUE TITLE
Are there any routing capabilities in Lwan?

### ISSUE THREAD

**Issue by DJviolin** [lpereira/lwan#156]
Right now I'm building a static Express website which is heavily using routing and handlebars templating with Json objects. With these tools I creating the immersion of a dynamic site.

I know there's Mustache templating in Lwan by default. But is there any change to see some basic routing features, like reading query parameters and strings from URLs?

**Comment by lpereira** [comment]
You can use query strings: `/something?param1=value1&param2=value2`, and use the `rewrite` module to make it look nicer on the eyes (and even do some basic validation right there, such as only accepting numeric digits for a certain value).

There's currently no shortcut for this kind of thing, though.

**Comment by lpereira** [comment]
I'm closing this issue, but feel free to reopen or create a new one.
