### ISSUE TITLE
Interest in Handling other status codes

### ISSUE THREAD

**Issue by HalosGhost** [lpereira/lwan#169]
It looks like there are 16 HTTP Status codes handled at the moment. There are more than 30 official status codes. Admittedly, many of them do not make sense for lwan to handle at the moment (e.g., ``101 Switching Protocols`` since lwan only handles HTTP at the moment).

But, I was wondering what the interest might be in adding more of the status codes to the code list (the ``lwan_http_status_t`` ``enum``, the ``RESP()`` macro list and the ``lwan_http_status_as_descriptive_string()`` function).

If there is some interest in adding these, I would be glad to open a PR for them, though I guess I would be interested to know which codes I should seek to add.

**Comment by lpereira** [comment]
As discussed on IRC, it's best to implement these on an as-needed basis, IMHO. You're still free to make a PR, though; I wouldn't mind merging such patch.
