### ISSUE TITLE
Build warning on 32-bit ARM

### ISSUE THREAD

**Issue by hdante** [lpereira/lwan#171]
[ 84%] Building C object common/CMakeFiles/lwan-static.dir/strbuf.c.o
/home/hdante/lwan/common/strbuf.c: In function ‘find_next_power_of_two’:
/home/hdante/lwan/common/strbuf.c:44:21: warning: conversion to ‘size_t {aka unsigned int}’ from ‘long long unsigned int’ may alter its value [-Wconversion]
         return 1ULL << (size_bits - __builtin_clzll((unsigned long long)number));
                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by lpereira** [comment]
That doesn't make much sense -- that line should only be compiled if `sizeof(size_t) == sizeof(unsigned long long)`, which is not the case for this architecture as the compiler says. Do you have a better suggestion to improve those checks?

**Comment by hdante** [comment]
It looks like a gcc bug and it might make sense to open a bug report. You can probably work around it by replacing the integer literals by a size_t constant with value of 1.

Note: in C11 you should replace this kind of check by a generic selection.
