### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by dedok** [lpereira/lwan#175]
Hi all!

I'm looking for embeddable web-server for project Tarantool(github.com/tarantool/tarantool)
And - guys - I've found this project! :)
But before go any further I wanna know
- There can I find API documenration, or I need read source code(that's not a problem)?
- I've found that you are using coro - like we do! - and I'm wondering can I don't use them?

**Comment by lpereira** [comment]
There's currently no API documentation. Your best bet is to look around for usages in the test suite, techempower, and freegeoip subdirectories. I've started [writing documentation](https://lwan.ws/docs/) but life got in the way; I'll eventually resume that effort. Feel free to ask questions (either by email or opening a ticket) if something isn't clear enough from the examples, though.

As for coroutines, they're heavily tied to how Lwan works internally. There's no way Lwan can be used without them.

**Comment by dedok** [comment]
Thanks for the reply! I'll keep in mind this project.
