### ISSUE TITLE
No data in POST request with charset in content-type

### ISSUE THREAD

**Issue by fischermario** [lpereira/lwan#177]
I came across a very strange problem: I tried to build a small frontend for my API that includes the ability to send some text out from a textarea to the server using a POST request. For some convenince I am doing this with Javascript. Specifically I am doing this by using jQuery. It fails every time whatever I try.

After some debugging in the browser I found out that jQuery is sending this content-type:
> application/x-www-form-urlencoded; charset=UTF-8

Now lwan just checks for the exact (!) match on
> application/x-www-form-urlencoded

and only then the POST parameters get processed.

I did some research to find out if this maybe is some "stepping out of the line" by jQuery. It turns out that the W3C specification (look at [this document](https://www.w3.org/TR/html5/forms.html#application/x-www-form-urlencoded-encoding-algorithm), scroll to the end of the section right before the start of "4.10.22.7 Multipart form data") says:
> Parameters on the application/x-www-form-urlencoded MIME type are **_ignored_**. In particular, this MIME type does not support the charset parameter.

I have written a small patch that slightly modifies the "parse_post_data" function in "common/lwan-request.c" without hurting the very elegant logic :-) Now the function checks if at least (!) "application/x-www-form-urlencoded" is present. Any stuff that comes afterwards is ignored.

That works for me.

[lwan-post-content-type-charset.patch.txt](https://github.com/lpereira/lwan/files/555195/lwan-post-content-type-charset.patch.txt)

PS.: Don't worry, I am still working on the coro topic. My spare time is just a little limited right now.

**Comment by lpereira** [comment]
Nice catch! Thanks for the patch.
