### ISSUE TITLE
keep alive tansfer to non keep alive will segment fault

### ISSUE THREAD

**Issue by dangyajun** [lpereira/lwan#181]
http client keep alive mode  tansfer to non keep alive will cause segment fault at lwan-coro.c in function run_or_recurse

23781 lwan-coro.c:319 coro_defer_any() coro start = 0x7ffff0c817c0, coro end = 0x80001645f800
Coro 0x7ffff1a59600 exhausted space for deferred callback.

**Comment by lpereira** [comment]
Thanks for the report. This isn't a segmentation fault, but is indeed a bug. How many requests have been made in the same connection before changing it from keep-alive to close?

**Comment by dangyajun** [comment]
I run a thousand clients for a stressing, The program die soon before transfer to non keep alive mode. And the packets sent by client is less than a thousand. Commonly died at five hundred.

**Comment by lpereira** [comment]
I can't really reproduce here; could you please provide some way to reproduce this? Maybe a wrk script, or a curl command line?

**Comment by dangyajun** [comment]
Sorry, I can't. But you can download tools HttpTest4Net here(http://www.cnblogs.com/smark/p/3636873.html).It is an windows version .
you can use it reproduce the problem.

**Comment by lpereira** [comment]
Thanks. I'll see what I can do with that program.

**Comment by lpereira** [comment]
This should be fixed as part of the fix for #264
