### ISSUE TITLE
Custom Paths

### ISSUE THREAD

**Issue by GuacheSuede** [lpereira/lwan#183]
Hi Ipereira,
how does one go about writing custom paths such as `/hello/John` and getting `John` as a param,
and different  paths leading to different handlers ?

Thank You

**Comment by GuacheSuede** [comment]
@lpereira

**Comment by lpereira** [comment]
For the first question, you just have a URL map handler that matches "/hello/": making a request to "/hello/John" will call the appropriate handler. The URL in the request struct will be modified, having the "/hello/" prefix stripped, leaving only "John" in it.

**Comment by GuacheSuede** [comment]
Alright sure Thank you @lpereira , any plans to make a custom url params support eg. `user/:id` ?

**Comment by lpereira** [comment]
You can use the rewrite module and rewrite `/user/(%a+)/(%a+)` to, say, `/user_action?action=%2&user=%1`. Lwan provides functions to obtain variables passed to the query string.

**Comment by GuacheSuede** [comment]
@lpereira those are query params though, what about params part of string ?

**Comment by lpereira** [comment]
If you use the rewrite module like that, requests to, say, "/user/John/display" will be rewritten so that "/user_action?action=display&user=John" is called instead. You could even have different handlers, for instance, so that Lwan will give a 404 for invalid actions:

     rewrite /user/ {
          pattern ^(%a+)/(%a+) { rewrite as = /user_%2?id=%1 }
     }
     &user_display /user_display
     &user_delete /user_delete

(`user_display` and `user_delete` are handler functions.)

**Comment by GuacheSuede** [comment]
@lpereira Alright Thank You, final question if you dont mind, how do i specify GET/POST handlers for the route ?

**Comment by lpereira** [comment]
The wiki is slightly outdated but there's a tutorial that might help you: https://github.com/lpereira/lwan/wiki/Using-Lwan-as-a-Library

**Comment by GuacheSuede** [comment]
@lpereira Yes I saw that, dint say how to specify different handler for routes, different GET/POST/DELETE /etc. handlers

**Comment by lpereira** [comment]
You have only one handler per path. The handler has to dispatch based on the method (call lwan_request_get_method(), switch on REQUEST_METHOD_GET, ..._POST, ..._DELETE, etc).

**Comment by lpereira** [comment]
I'm closing this issue as it wasn't really an issue to be fixed; feel free to reopen it, however.

**Comment by GuacheSuede** [comment]
Aight Sure, its fixed now, Thanks @lpereira
