### ISSUE TITLE
Is there a way to pass parameters to handlers such as db conn objects ? 

### ISSUE THREAD

**Issue by GuacheSuede** [lpereira/lwan#190]
eg ` { .prefix = "/hello", .handler = helloWorld(conn)}`
Or perhaps though lambdas

**Comment by lpereira** [comment]
Yes, there's space for a void*. Follow the tutorial, it's explained there.

**Comment by GuacheSuede** [comment]
are you talking abt this `  void *data __attribute__((unused))` ?

**Comment by lpereira** [comment]
The `data`  member in the `struct lwan_url_map` will be passed to the handler as the `data` parameter, yes. In the case of the part you've pasted, this handler has no use for data, so it was marked as unused to keep the compiler from complaining.

**Comment by GuacheSuede** [comment]
Alright sure, Thank you.
