### ISSUE TITLE
Getting Segmentation Fault running nlohmann/json inside a handler.

### ISSUE THREAD

**Issue by GuacheSuede** [lpereira/lwan#191]
This is the code 

    static enum lwan_http_status uHandler(struct lwan_request *request, struct lwan_response *response, void *data){
       static struct lwan_key_value rheaders[] = {
        { .key = "Access-Control-Allow-Origin", .value = "*" },
       };    
     json j;`

     j["pi"] = 3.141;`
    
     std::cout <<  j.dump()    << std::endl;
    return HTTP_OK;

    }

Thank You

**Comment by GuacheSuede** [comment]
The same thing happens for rapidjson and staticjson libs

**Comment by lpereira** [comment]
@GuacheSuede It took me a while to fix an esoteric crashing issue, but it seems I got it now. Could you please recheck?

**Comment by lpereira** [comment]
Closing as fixed.

**Comment by hariseenivasan** [comment]
Is this issue really fixed? 
#191 and #203  have been closed with a cyclic dependency and no confirmation of any fixes.

**Comment by lpereira** [comment]
The issue where Lwan would crash when using floating pointing numbers with SSE instructions have been fixed, yes.
