### ISSUE TITLE
abort_on_open_directories always abort

### ISSUE THREAD

**Issue by buf1024** [lpereira/lwan#198]
I am sorry to trouble you again, I don't quit understand the function `abort_on_open_directories`, It always abort in my computer. my os is Ubuntu  16.04, I start lwan using `sudo ...`. the configuration I add:  

```
traitjacket {
  user = buf1024                            # the user
  chroot = /home/buf1024            # the user's home dir
}     
```
it aborts at:

``
       lwan_status_critical(
                "The directory '%s' is open (fd %s), can't chroot",
                path, ent->d_name);
``

did i do something wrong?

**Comment by lpereira** [comment]
Are you declaring the straitjacket section before the listener section?
Lwan acts on configuration files as it reads it, so this must be declared
before modules are able to open their directories.

This function exists to guarantee that no directory handles will exist when
enabling a chroot, which would allow escaping.

Once a straitjacket section has been declared, all directories  must be
declared as a relative path to the chroot.

**Comment by buf1024** [comment]
@lpereira thanks, straitjacket section is after the listener section, my configuration problem.

**Comment by lpereira** [comment]
Alright. Closing issue, then.
