### ISSUE TITLE
Bad directory listing of / in lwan-mod-serve-files.c

### ISSUE THREAD

**Issue by dubhater** [lpereira/lwan#200]
I'm running lwan like this for the purpose of serving a few files:
```sh
lwan --root . --listen localhost:1234
```
The directory listing of / contains unusable links. They look like this:
```html
    <tr>
      <td><img src="/icons/file.png" alt="FILE"></td>
      <td><a href="&#x2f;/PKGBUILD">PKGBUILD</a></td>
      <td>application/octet-stream</td>
      <td>901B</td>
    </tr>
    <tr>
      <td><img src="/icons/folder.png" alt="DIR"></td>
      <td><a href="&#x2f;/src">src</a></td>
      <td>directory</td>
      <td>17B</td>
    </tr>
```
If I click on PKGBUILD, both Firefox and Chromium try to open ``http://PKGBUILD`` instead of ``http://localhost:1234/PKGBUILD``.

If I type ``http://localhost:1234/src`` in the address bar, the directory listing for that folder contains proper links.

I tried removing the slash at column 38 here: https://github.com/lpereira/lwan/blob/9c2a7456b3e527d1186cb70bae3c6d4c48d2124e/common/lwan-mod-serve-files.c#L211 That "fixed" the links in /, but broke the links in /src/.

**Comment by dubhater** [comment]
By the way, the output of ``--help`` mentions ``--listener``, but the correct name is ``--listen``.

**Comment by lpereira** [comment]
Thanks for reporting the bug.  I'll try fixing it as soon as I have access to a personal computer again.

**Comment by lpereira** [comment]
Seems to be fixed now -- thanks for reporting the issue! Feel free to reopen if the issue still persists.
