### ISSUE TITLE
How to upload files?

### ISSUE THREAD

**Issue by cgoxopx** [lpereira/lwan#201]
Error:413

**Comment by cgoxopx** [comment]
[ https://github.com/cgoxopx/YRSSF/blob/master/core/webserver.hpp]( https://github.com/cgoxopx/YRSSF/blob/master/core/webserver.hpp)

**Comment by lpereira** [comment]
File uploading isn't supported yet.

**Comment by asymness** [comment]
Is file uploading supported now?

**Comment by lpereira** [comment]
No, it's not supported.  It should be possible to do it yourself in a handler by adding support for multipart MIME, I imagine.
