### ISSUE TITLE
Empty query param invalidates the entire set

### ISSUE THREAD

**Issue by juntalis** [lpereira/lwan#211]
Noticed some odd behavior with the query params parsing where an empty parameter would result in the whole query string being dropped and none of the params being added to the request. Looked into it a bit and found the cause in [parse_key_values](https://github.com/lpereira/lwan/blob/master/src/lib/lwan-request.c#L364). Since `url_decode` returns the length of the decoded value, (not including the trailing zero) an empty value would abort the parsing.

I was able to avoid this behavior by changing line 364 to:

```c
            value = "";
```

I feel like that's probably not accounting for the other use cases of `parse_key_values`, though.

**Comment by lpereira** [comment]
Good catch! Let me fix this.

**Comment by lpereira** [comment]
This is most likely fixed now; if the issue persists, please reopen the issue.
