### ISSUE TITLE
linking the hello_world example against liblwan.so fails

### ISSUE THREAD

**Issue by diviaki** [lpereira/lwan#223]
gcc -o hello hello.c -I lwan/src/lib/ -Llwan/build/src/lib/ -llwan

    /tmp/cc4jC9OA.o: In function `hello_world':
    hello.c:(.text+0x6d): undefined reference to `strbuf_set_static'
    collect2: error: ld returned 1 exit status

**Comment by diviaki** [comment]
looks like it isn't exposed:

    $ readelf -s lwan/build/src/lib/liblwan.so|grep strbuf_set_static
    $

**Comment by lpereira** [comment]
That's true: any symbols that do not begin with `lwan_` are not being [exported any longer](https://github.com/lpereira/lwan/blob/master/src/lib/liblwan.sym).  The `strbuf_` symbols need to be renamed to `lwan_strbuf_`. Rationale: #217.

**Comment by diviaki** [comment]
need a hand with that?

**Comment by lpereira** [comment]
Sure, help is always appreciated.

**Comment by lpereira** [comment]
I ended up renaming it already. The wiki and web page have been updated.

**Comment by diviaki** [comment]
That's great.
Note that I still see an occurrence of strbuf_set_static on lwan.ws though.

**Comment by diviaki** [comment]
Linking works fine now, closing.
