### ISSUE TITLE
First basic example in wiki fails to link

### ISSUE THREAD

**Issue by diviaki** [lpereira/lwan#224]
/tmp/ccP16mO3.ltrans1.ltrans.o: In function `parse_listener_prefix':
    <artificial>:(.text+0x182c): undefined reference to `__start_lwan_module'
    <artificial>:(.text+0x1833): undefined reference to `__stop_lwan_module'
    <artificial>:(.text+0x1867): undefined reference to `__stop_lwan_module'
    /tmp/ccP16mO3.ltrans1.ltrans.o: In function `setup_from_config':
    <artificial>:(.text+0x1f6f): undefined reference to `__start_lwan_module'
    <artificial>:(.text+0x1f76): undefined reference to `__stop_lwan_module'
    <artificial>:(.text+0x1fa7): undefined reference to `__stop_lwan_module'
    collect2: error: ld returned 1 exit status

**Comment by diviaki** [comment]
This is now fixed by copy pasting parts of src/bin/lwan/CMakeLists.txt

**Comment by lpereira** [comment]
Thanks for foxing this!
