### ISSUE TITLE
wiki rot: handler not found when following guide

### ISSUE THREAD

**Issue by diviaki** [lpereira/lwan#225]
Follow the wiki up to the point where it added the hello handler to minimal.c, and says:
"Rebuild and try running it again."

I did try it but...:

    Loading configuration file: lwan.conf.
    Error on config file "lwan.conf", line 32: Could not find handler "hello_world".

But hey:

     $ readelf -s lwan|grep hello_ 
    60: 0000000000004480    69 FUNC    LOCAL  DEFAULT   13 hello_world

**Comment by lpereira** [comment]
I've changed recently how to declare a handler. The wiki should be fixed now.

**Comment by lpereira** [comment]
In fact, if you run `lwan --handlers` or `lwan --modules`, it should now list all handlers and modules. This should make it easier to write configuration files.

**Comment by diviaki** [comment]
OK thanks QC passed :)

**Comment by diviaki** [comment]
note: example https://lwan.ws is still out of date

**Comment by lpereira** [comment]
Fixed webpage as well.
