### ISSUE TITLE
Coroutines can be used standalonish?

### ISSUE THREAD

**Issue by Globik** [lpereira/lwan#231]
I'm wondering if lwan's coroutines can work standalone from lwan server? Let's say as a library? Can be compiled on his own or it's impossible without the lwan's whole stuff?

**Comment by dakerfp** [comment]
They can if you respect the license and make some minor changes.
Their dependencies are ucontext, lwan's data structures and stdlib.

**Comment by Globik** [comment]
Hi @dakerfp I apreciate your answer.
I'll try to compile a small programm using lwan lib. So far I'm just studying the C language. Just couriose about if I can bind the libuv instance with lwan's coroutines. Just because here there are real life practical use cases from lwan's source code I mean "coroutines".

**Comment by sjnam** [comment]
@Globik https://github.com/sjnam/lwan-coro

**Comment by lpereira** [comment]
Closing issue as the question has been answered. Feel free to reopen if that's not the case.

**Comment by Globik** [comment]
@sjnam thank you so much, it's wonderful.
@lpereira  thank you too, it's a nice job.

**Comment by Globik** [comment]
How to coroutinify callbacks??
