### ISSUE TITLE
Possible memory leak in src/bin/tools/mimegen.c : compress_output()

### ISSUE THREAD

**Issue by D4N** [lpereira/lwan#236]
There is a potential memory leak in the function `static char *compress_output(const struct output *output, size_t *outlen)` in `src/bin/tools/mimegen.c:83`.

The issue arises when zopfli is not available and zlib is used. Assuming that the call to `compress2` would set `outlen` to 0, then this function exits with `NULL`. However, the malloc'd struct `compressed` is not freed in that case.

The fix should be simple, just add a `free(compressed)` before `return NULL`.

This issue was found by [infer](https://github.com/facebook/infer).

**Comment by lpereira** [comment]
Fixed, thanks!
