### ISSUE TITLE
list.h not installed properly

### ISSUE THREAD

**Issue by HalosGhost** [lpereira/lwan#239]
Looks like this [``CMakeLists.txt``](https://github.com/lpereira/lwan/blob/master/src/lib/CMakeLists.txt#L116-L132) file is missing ``list.h`` which results in the following when trying to use ``lwan.h`` in a project:

```
In file included from main.c:1:
In file included from /usr/include/lwan/lwan.h:40:
/usr/include/lwan/timeout.h:34:10: fatal error: 'list.h' file not found
#include "list.h"
         ^~~~~~~~
1 error generated.
make: *** [Makefile:30: bin] Error 1
```

I believe all that needs to be done is adding a line to make sure ``list.h`` is installed as well.

Thank you!

**Comment by lpereira** [comment]
Fixed, thanks for reporting!

**Comment by HalosGhost** [comment]
Happily, I have another one incoming to expose some symbols needed for template authoring. :)
