### ISSUE TITLE
setjmp/longjmp fallback for platforms without ucontext

### ISSUE THREAD

**Issue by lpereira** [lpereira/lwan#242]
Some operating systems lack the deprecated ucontext.h header, which is used as the fallback method to implement coroutines on systems that are not i386 or x86_64.  One example is OpenBSD: while it's fine on x86 systems (as, by default, its C compiler respects the SysV ABI, so the assembly routines can be used), Lwan can't be built in its ARM port.

**Comment by mochechan** [comment]
**Lwan can't be built in its ARM port.**
So, do you mean that the Lwan cannot compiled in ARM, such as Raspberry PI, Jetson Nano?
