### ISSUE TITLE
Any plans to merge websocket-experimental with master branch ?

### ISSUE THREAD

**Issue by GuacheSuede** [lpereira/lwan#254]

**Comment by lpereira** [comment]
Yes, there are plans, but the API is, as the name says, experimental. There are lots of things I have to fix first. Some of them, in fact, are being slowly fixed in the master branch.

**Comment by GuacheSuede** [comment]
Alright Gotcha, Looking forward to it !

**Comment by GuacheSuede** [comment]
@lpereira I've got a question if you dont mind, writing lwan in c, what difficulties have u faced that would have been better served by c++ ?

**Comment by lpereira** [comment]
Merged.
