### ISSUE TITLE
Support custom headers

### ISSUE THREAD

**Issue by quangIO** [lpereira/lwan#255]
Fully supporting CORS would require knowing `Origin` header. Besides, I think it would be really useful for writing custom handler if we can access custom headers information instead of just predefined ones. May be something like this?
```C
struct lwan_request_parser_helper {
...
    struct lwan_key_value_array extra_headers;
};

lwan_request_get_header(struct lwan_request *request, const char *key) {
    return value_lookup(&request->helper->extra_headers, key);
}
```

Btw, what a beautiful piece of engineering! I ask for this because I am making a framework having lwan as a backend at https://github.com/KwangIO/kwang

**Comment by lpereira** [comment]
This should be working fine. Please let me know if it works for you.

**Comment by quangIO** [comment]
Thanks, it's working great!
