### ISSUE TITLE
lwan.pc compiled on aarch64 has an errant Libs line

### ISSUE THREAD

**Issue by HalosGhost** [lpereira/lwan#259]
When compiling `lwan` on aarch64, the created `lwan.pc` file adds, along with `-lm`, an `m` entry to the `Libs` line:

```
Name: lwan
Description: Scalable, high performance, experimental web server
Version: 7e212b1
Requires: 
prefix=/usr/local
includedir=${prefix}/include/lwan
libdir=${prefix}/lib
Libs: -L${libdir} -llwan /usr/lib/libz.so -lpthread -llua5.1 m -llua5.1 -lm
Cflags: -I${includedir} -include ${prefix}/include/lwan/lwan-build-config.h
```

Inevitably, as `m` is not a recognized a flag or file, it results in the following error when attempting to link against `lwan` as a dynamic library:

```console
$ gcc `pkg-config --libs lwan` main.c
gcc: error: m: No such file or directory
```

Briefly looking at `grep -rniI 'ADDITIONAL_LIBRARIES'`, it looks like there are only a few places that could be involved with this issue. In particular, it looks like line 45 from the main CMakeLists.txt is the most likely culprit:

```
list(APPEND ADDITIONAL_LIBRARIES "-l${LUA_LIBRARIES} ${LUA_LDFLAGS}")
```

Any thought on how to fix this?

**Comment by lpereira** [comment]
Thanks for finding this.  Yes, this is wrong; instead of appending the libraries and ldflags, we should append only ldflags, without prepending `-l`.

**Comment by HalosGhost** [comment]
Lovely! Glad it doesn't sound like a terribly hard fix. I'll PR it tonight if you would like.

**Comment by lpereira** [comment]
No, it's pretty trivial.  Feel free to send a PR.
