### ISSUE TITLE
TCP/UDP

### ISSUE THREAD

**Issue by webandbusiness** [lpereira/lwan#266]
Hello, can it handle TCP / UDP service / server? 
(IOT applications are next future)
If yes How?
If not Why?
Regards

**Comment by dakerfp** [comment]
It could be just simpler handle your own TCP connection by itself. You don't need all the HTTP infrastructure to handle that, although you could use some of lwan's abstractions such as co routines to help with some kinds of work load. However, that's still very general. You could be more specific on what you expect.

**Comment by lpereira** [comment]
Closing as original author didn't respond in over a year.
