### ISSUE TITLE
Can't compile on macOS due to fwrite_unlocked().

### ISSUE THREAD

**Issue by xfbs** [lpereira/lwan#269]
I can't seem to compile the recent version on macOS, due to a usage of `fwrite_unlocked()`, which doesn't exist on macOS.

The man page for this says:

>   The nonstandard *_unlocked() variants occur on a few UNIX systems, and are available in recent glibc. They should probably not be used.

Could you maybe switch to using standard functions, or add a check/conditional?

**Comment by lpereira** [comment]
I've just pushed a fix to this.  Thanks for the report.  I've recently moved so my test setup with an old Mac mini has not been put together yet, so the build isn't being monitored by the buildbot.
