### ISSUE TITLE
Handling 0 bytes files

### ISSUE THREAD

**Issue by murataka** [lpereira/lwan#281]
Hello , i just installed lwan on freebsd with zfs file system.

after starting lwan , update files to be served,

When i put a zero bytes index.html in wwwroot, the response does not finish.

root@rescue:~ # cd tmp
root@rescue:~/tmp # cd wwwroot/
root@rescue:~/tmp/wwwroot # touch index.html

try to browse the server...

**Comment by murataka** [comment]
the case also happens with other files than index.html.

**Comment by lpereira** [comment]
Works fine here on Linux.  What's the behavior your're seeing? I don't have a FreeBSD system with ZFS to test this.

**Comment by lpereira** [comment]
Indeed that's a problem in FreeBSD, thanks for reporting.  The filesystem doesn't seem to matter (my FreeBSD machine doesn't have a ZFS filesystem).

**Comment by lpereira** [comment]
Should be fixed now.  Please confirm (and feel free to reopen if it isn't).

**Comment by murataka** [comment]
Confirmed. Problem solved 👍
