### ISSUE TITLE
There has memory leak when call lwan_request_get_post_param()

### ISSUE THREAD

**Issue by fangxinmiao** [lpereira/lwan#283]
There has memory leak when call `lwan_request_get_post_param()`。

**Comment by lpereira** [comment]
I can't find the leak, how did you find it?

That function will allocate an array the first time it's called, which will
eventually be freed. It's not always freed right after the request has been
handled, but it will if either the connection closes, or after a few
requests have been handled by the same connection. This might appear as a
memory leak until it's freed but it's by design.

**Comment by fangxinmiao** [comment]
I use wrk to test it. The handler is:

```c
static enum lwan_http_status foobar(struct lwan_request *request,
        struct lwan_response *response, void *param)
{
    const char *value __attribute__((unused)) = 
            lwan_request_get_post_param(request, "key");
    lwan_strbuf_set_static(response->buffer, "foobar", 6);
    return HTTP_OK;
}
```

The lua script is:

```lua
wrk.method = "POST"
wrk.body   = "key=12345678901234567890123456789012345678901234567890123456789012345678901234567890"
wrk.headers["Content-Type"] = "application/x-www-form-urlencoded"
```

Now run the wrk benchmark:

```bash
wrk -t 2 -c 100 -d 24h --script=foobar.lua http://localhost:8080/foobar
``

You will find that the memory of the service will continue to rise.

**Comment by lpereira** [comment]
Thanks!  I'll take a look at this closely with [Massif](https://valgrind.org/docs/manual/ms-manual.html).

**Comment by lpereira** [comment]
I was able to reproduce it here.  This is very odd indeed!

![Screenshot from 2020-07-10 09-15-35](https://user-images.githubusercontent.com/15001/87175776-a8d4fd80-c2c8-11ea-89bd-b8f277ab88b3.png)

**Comment by lpereira** [comment]
This is interesting.  It's also the cause of a performance regression I'm seeing in the TechEmpower Web Framework benchmarks.  Looking into this now.

**Comment by lpereira** [comment]
It seems that I've found and fixed the issue. Can you please confirm if it still persists?
