### ISSUE TITLE
Segment fault when return 401 status code

### ISSUE THREAD

**Issue by fangxinmiao** [lpereira/lwan#286]
When return 401 status code, lwan must occur segment fault. Sample code as blow:

```c
LWAN_HANDLER(hello_world)
{
    static const char message[] = "unauthorized";

    response->mime_type = "text/plain";
    lwan_strbuf_set_static(response->buffer, message, sizeof(message) - 1);

    return 401;
}
```

**Comment by lpereira** [comment]
Indeed it does, thanks for finding this one!

Although you should be using the "authorization" option to emit 401s instead.

**Comment by lpereira** [comment]
Pushed a fix; please reopen if you still see the issue.
