### ISSUE TITLE
Put LWAN on TechEmpower Framework Benchmark again :3

### ISSUE THREAD

**Issue by kokizzu** [lpereira/lwan#291]
To boost LWAN's popularity!

https://github.com/TechEmpower/FrameworkBenchmarks/issues/4147

**Comment by lpereira** [comment]
It's back there since the current public round!

**Comment by kokizzu** [comment]
oh right it's available on other benchmark section '__') 
i was only check "data updates" benchmark section

**Comment by lpereira** [comment]
That's the only one that's not currently implemented 😂

There's a big performance regression in the preview rounds but I don't have
time to look at it, though.
