### ISSUE TITLE
Does not build on platforms where size_t is not 64-bit

### ISSUE THREAD

**Issue by angelsl** [lpereira/lwan#293]
https://github.com/lpereira/lwan/commit/62a25b122c4af32a3d60287a0a65b3c25f55a24f#diff-94ee1f5fd74ecb92be0520d80665a5a8R124

**Comment by lpereira** [comment]
It's been a while since I built Lwan on a 32-bit platform; it used to work fine.  Which platform are you on (processor architecture, OS, C library, etc)?

**Comment by angelsl** [comment]
I was trying to build on Debian Stretch armel. I linked the offending commit and line, actually. Not sure why `size_t` needs to be used there..

**Comment by lpereira** [comment]
That's because a 64-bit integer is passed to a function that expects a size_t.  I'll look into this over the weekend; thanks for reporting.  (Will probably set up a 32-bit buildbot instance too.)

**Comment by lpereira** [comment]
This should be fixed. Please reopen if you still see the issue.

**Comment by angelsl** [comment]
Thanks!
