### ISSUE TITLE
`make install` fails because of missing `queue.h`

### ISSUE THREAD

**Issue by UgiNyaa** [lpereira/lwan#306]
I noticed that in commit abf0d8e7520d482839f620203e3589e56b5b1e68 the files `queue.c` and `queue.h` were removed. The source reference of `queue.c` inside `src/lib/CMakeLists.txt` was also removed, but not the `queue.h` reference on line 161: https://github.com/lpereira/lwan/blob/4f5ecdeb75bd2dc1855997dcb52924fc53a71ac8/src/lib/CMakeLists.txt#L161

This error doesn't cause much problems unless you try to install lwan as a library with its corresponding header files. At this point I imagine the build system tries to copy the `queue.h` header file to its suitable place, but doesn't find the file. I encountered this error today and was able to fix it by removing the `queue.h` line in `src/lib/CMakeLists.txt`.

Steps to reproduce the error:
1. `cd lwan`
2. `mkdir build && cd build`
3. `cmake ..`
4. `make`
5. `make install` (needs root privileges)

**Comment by lpereira** [comment]
Thanks for the report. If you don't mind, could you please send a PR fixing
the issue? I'm a bit far away from my personal computer.

(I'll add an "install" test later.)
