### ISSUE TITLE
is there anything faster than lwan?

### ISSUE THREAD

**Issue by hiqsociety** [lpereira/lwan#308]
is there anything faster than lwan?

i'm looking for the fastest c implementation with maximum number of concurrent keepalive or non keep alive connection

**Comment by lpereira** [comment]
That's a very difficult question to answer, because there are a lot of dimensions to benchmark against.  Although I can't claim that there isn't anything faster than Lwan, I'd say that it's pretty much up there as far as efficiency (if you consider low latency, high throughput, and conservative memory usage) goes with the leading pack of servers.

**Comment by hiqsociety** [comment]
thx for the great work. 
1. trying to understand what's the memory requirement per connection for lwan etc. do u know roughly how much mem is required per connection?

2. i was looking through online and found this
https://gist.github.com/lpereira/2154951

how much mem per coroutine for it too?

3. possible to benchmark (or provide feedback) against this? 
https://www.embedthis.com/

**Comment by lpereira** [comment]
1. The major memory requirement is the stack size for each coroutine. At the moment, this is about `4 * SIGSTKSZ`, which is about 8KB on x86-64 Linux (although this can be different).  A bit more memory per connection is necessary (at least 32 bytes per connection). So, for 10k connections, you'd need something in the ballpark of 320MB of RAM at least.
2. The coroutine implementation you posted was written by myself. It's a very old implementation that Lwan used to use, and the current version being used by the server is better.
3. Feel free to benchmark and post the results.

**Comment by hiqsociety** [comment]
amazing work!

32kb per connection is quite high. is coroutine the issue? maybe can use this one?
https://github.com/hnes/libaco

**Comment by lpereira** [comment]
It's not trivial to reduce this number. I've made a *lot* of experiments.
If it's a stackful coroutine, it's kinda difficult to carry around a stack
smaller than this number.

**Comment by hiqsociety** [comment]
ok thx. keep up the great work!
