### ISSUE TITLE
Fail to serve html from binary `lwan`

### ISSUE THREAD

**Issue by eecheng87** [lpereira/lwan#332]
Hi, thanks for your great work first.

I tried to run `lwan` under `lwan/build/src/bin/lwan` and used given `lwan.conf` and `wwwroot/` in the top level folder.
After launch `lwan`, I open browser with links: `http://0.0.0.0:8080/index.html`, then I get 404 not found.
I'm wondering do I missing anything?

Thanks in advance.

EDIT: By the same process, `lwan` works on my virtual machine (both my host and guest OS are Ubuntu 20.04). I have no idea what configuration go wrong on my host. Any troubleshooting?

**Comment by lpereira** [comment]
I apologize for not seeing this sooner! I changed email providers and some got lost in transit.

You might get 404 if the file you're trying to serve doesn't have world-readable permissions as well. It's usually a good idea to run lwan under strace (following forks, etc) when this happens to know what's happening.

Besides that, I don't really know what could be happening. Were you using straightjackets?
