### ISSUE TITLE
Low CPU utilization and low throughput in specific scenario

### ISSUE THREAD

**Issue by eecheng87** [lpereira/lwan#334]
Hi, I do some primitive tests on `lwan` and I found low CPU utilization and low throughput when requesting 50 KiB static files.
I using [wrk](https://github.com/wg/wrk) to benchmark `lwan`. Following is my CPU feature:
```
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              2
Model name:                      Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
```
By using wrk by `wrk -c 50 -d 5s -t 2 http://localhost:8080/a50.html`, I got the throughput: 1615 (req/sec). And I found CPU utilization is really low (~20%) by `htop`.

I tweak the parameter of `sendfile` in `lwan_sendfile` in lwan-io-wrapper.c. I replace `chunk_size` with `count`, the code would be:
```
void lwan_sendfile(struct lwan_request *request,
                   int in_fd,
                   off_t offset,
                   size_t count,
                   const char *header,
                   size_t header_len)
{
...
    size_t chunk_size = LWAN_MIN(count, (1ul << 14) - header_len);
    size_t to_be_written = count;

    assert(header_len < (1ul << 14));

    lwan_send(request, header, header_len, MSG_MORE);

    while (true) {
        ssize_t written = sendfile(request->fd, in_fd, &offset, count);
        if (written < 0) {
 ...
        }
```
By transmitting file in "one time", I get the throughput, with same configuration, 56754 (req/sec). (CPU almost reach 100% in this scenario).

If there is any information I missed, please tell me. Thanks in advance!

**Comment by lpereira** [comment]
Thanks for the report! There's definitely room for improvement there.

I know that there are issues with sendfile() when using kTLS, for instance, so this might require more testing/investigation. For instance, I don't know how much memory the kernel allocates to encrypt the buffer, so passing the file size might not be a good idea.

Another thing to consider is the amount of clients; I usually test with 10k clients rather than just 50, and if a sendfile call for each individual file takes too long, the latency has undesirable spikes. Maybe it should be capped at, I don't know, the size of a pipe buffer (because sendfile is kinda like splice)? I don't know.

On Sun, Mar 13, 2022, at 12:43 AM, Steven Cheng wrote:
> 
> 
> 
> I do some primitive tests on `lwan` and I found low CPU utilization and low throughput when requesting 50 KiB static files.
> I using wrk <https://github.com/wg/wrk> to benchmark `lwan`. Following is my CPU feature:
> 
> `CPU(s):                          4
> On-line CPU(s) list:             0-3
> Thread(s) per core:              2
> Model name:                      Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
`
> By using wrk by `wrk -c 50 -d 5s -t 2 http://localhost:8080/a50.html`, I got the throughput: 1615 (req/sec). And I found CPU utilization is really low (~20%) by `htop`.
> 
> I tweak the parameter of `sendfile` in `lwan_sendfile` in lwan-io-wrapper.c. I replace `chunk_size` with `count`, the code would be:
> 
> `void lwan_sendfile(struct lwan_request *request,
>                    int in_fd,
>                    off_t offset,
>                    size_t count,
>                    const char *header,
>                    size_t header_len)
> {
> ...
>     size_t chunk_size = LWAN_MIN(count, (1ul << 14) - header_len);
>     size_t to_be_written = count;
> 
>     assert(header_len < (1ul << 14));
> 
>     lwan_send(request, header, header_len, MSG_MORE);
> 
>     while (true) {
>         ssize_t written = sendfile(request->fd, in_fd, &offset, count);
>         if (written < 0) {
>  ...
>         }
`

**Comment by lpereira** [comment]
Apparently, nginx limits this to 2MB by default. Maybe use 1<<21 instead of 1<<14 in the chunk size would be a good idea, then?

On Sun, Mar 13, 2022, at 12:15 PM, L. Pereira wrote:
> Thanks for the report! There's definitely room for improvement there.
> 
> I know that there are issues with sendfile() when using kTLS, for instance, so this might require more testing/investigation. For instance, I don't know how much memory the kernel allocates to encrypt the buffer, so passing the file size might not be a good idea.
> 
> Another thing to consider is the amount of clients; I usually test with 10k clients rather than just 50, and if a sendfile call for each individual file takes too long, the latency has undesirable spikes. Maybe it should be capped at, I don't know, the size of a pipe buffer (because sendfile is kinda like splice)? I don't know.
> 
> On Sun, Mar 13, 2022, at 12:43 AM, Steven Cheng wrote:
>> 
>> 
>> 
>> 
>> I do some primitive tests on `lwan` and I found low CPU utilization and low throughput when requesting 50 KiB static files.
>> I using wrk <https://github.com/wg/wrk> to benchmark `lwan`. Following is my CPU feature:
>> 
>> 
>> `CPU(s):                          4
>> On-line CPU(s) list:             0-3
>> Thread(s) per core:              2
>> Model name:                      Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
`
>> By using wrk by `wrk -c 50 -d 5s -t 2 http://localhost:8080/a50.html`, I got the throughput: 1615 (req/sec). And I found CPU utilization is really low (~20%) by `htop`.
>> 
>> I tweak the parameter of `sendfile` in `lwan_sendfile` in lwan-io-wrapper.c. I replace `chunk_size` with `count`, the code would be:
>> 
>> `void lwan_sendfile(struct lwan_request *request,
>>                    int in_fd,
>>                    off_t offset,
>>                    size_t count,
>>                    const char *header,
>>                    size_t header_len)
>> {
>> ...
>>     size_t chunk_size = LWAN_MIN(count, (1ul << 14) - header_len);
>>     size_t to_be_written = count;
>> 
>>     assert(header_len < (1ul << 14));
>> 
>>     lwan_send(request, header, header_len, MSG_MORE);
>> 
>>     while (true) {
>>         ssize_t written = sendfile(request->fd, in_fd, &offset, count);
>>         if (written < 0) {
>>  ...
>>         }
`

**Comment by eecheng87** [comment]
Hello @lpereira , really appreciate your reply!

I do a simple experiment to compare the performance between the primitive `lwan` and tweaking version which I mentioned in first message.

Following experiments are done under same hardware characteristic mentioned in first message. But with different wrk configuration. As your suggestion, I change my connection numbers larger to 1k. (greater than 1k will get socket errors in my computer)

![image](https://user-images.githubusercontent.com/38983968/158292122-802dde40-1a86-448c-9a96-bf2a8abc0eaf.png)
 
To be honest, I have no idea what lead this result. However, replace `chunk_size` with greater number such as `count` seems to be a good idea?

**Comment by lpereira** [comment]
Thanks for the numbers! It's interesting how the current code's performance drops sharply as the size increases, and then kinda stays in the same ballpark.

I don't think using count will be a good idea (e.g. for multi-megabyte/gigabyte files, we can't monopolize the I/O loop and need to yield so the next connection in line can do some work), but capping at 2MB or something seems like a good compromise.

Feel free to send a PR. (I can change this too but will only have some time during the weekend.)

   L.

**Comment by eecheng87** [comment]
Hello, thanks for suggestion.
I'll investigate more about the reasonable chunk size and then send a PR.
