### ISSUE TITLE
Problem with clean build and wsgi

### ISSUE THREAD

**Issue by avkapustin** [lpereira/lwan#336]
Hello,
at master branch, after commit https://github.com/lpereira/lwan/commit/279ea1857de7e9d30f910fecf2820e93779d0118 clean build failed with message
```
CMake Error at src/lib/CMakeLists.txt:56 (add_library):
  Cannot find source file:

    lwan-mod-wsgi.c
```

Looks like files lwan-mod-wsgi.{c, h} are not contains in this commit, only code to enable LWAN_HAVE_PYTHON

**Comment by lpereira** [comment]
Thanks for the report! It should be fixed now. (The WSGI module isn't yet upstreamed, as I'm working on it before I release it.)
