### ISSUE TITLE
Re-expose straitjackets

### ISSUE THREAD

**Issue by HalosGhost** [lpereira/lwan#337]
Commit e758902550d92c1c1ea6758ad2b22a8e73a6039e moved `lwan_straitjacket_enforce` and friends to `lwan-private.h`.
It seems like there's no C API equivalent/alternative available to drop privileges or isolate lwan to operate only in the directories where it should have access.

Is there an alternative that I've missed or a plan for a replacement?

**Comment by lpereira** [comment]
Fixed for a while, closing.
