### ISSUE TITLE
12% of cycles spent percent-decoding URLs

### ISSUE THREAD

**Issue by lpereira** [lpereira/lwan#351]
Replacing `url_decode()` with `strlen()` increases Lwan throughput by about 12% when servicing Hello, World responses. The current algorithm is not only very branchy, it also essentially does a byte-by-byte copy of every character that comes into the function, even if no decoding was necessary for that particular string.

**Comment by jvoisin** [comment]
a4fd3a6aaa1a733b28013ef9fcc7e320206632b9 improved the situation, but I'm sure that the two `for` loops could be mergedm so that the string doesn't have to be iterated on two times.

**Comment by lpereira** [comment]
The current version exchanges expensive byte-wise memory writes by fast byte scans+fast byte copies.  It's a good tradeoff.  Merging the two loops would increase the complexity quite a bit; it seems possible but I don't know yet how to strike a good performance/readability ratio.  If you have an idea on how to do this, please send a patch!

**Comment by lpereira** [comment]
It should be looping through the string just once now.  I haven't measured the performance yet.

**Comment by jvoisin** [comment]
The corresponding commit being f3a4785d5a6467ea20b404c86e2d0da30e93f8f8
