### ISSUE TITLE
get_number_of_cpus

### ISSUE THREAD

**Issue by nt3dnt** [lpereira/lwan#355]
lwan.c
static void get_number_of_cpus(struct lwan *l)
{
    long n_online_cpus = sysconf(_SC_NPROCESSORS_ONLN);
    long n_available_cpus = sysconf(_SC_NPROCESSORS_CONF);

//*****************************************************/
 https://man7.org/linux/man-pages/man3/sysconf.3.html
- _SC_NPROCESSORS_CONF
              The number of processors configured.  See also  get_nprocs_conf(3).
- _SC_NPROCESSORS_ONLN
              The number of processors currently online (available). See also [get_nprocs_conf(3)]

//*****************************************************/
    long n_online_cpus = sysconf(_SC_NPROCESSORS_ONLN);
    long n_available_cpus = sysconf(_SC_NPROCESSORS_ONLN);

**Comment by lpereira** [comment]
What is the issue with this function?

**Comment by lpereira** [comment]
Closing as the issue doesn't provide any context.  Feel free to reopen.
