### ISSUE TITLE
Is Gihtub embedded in smolsite?

### ISSUE THREAD

**Issue by sebelk** [lpereira/lwan#360]
Hi, sorry, but, by chance I visited https://smolsite.zip and I found that Firefox prevents for open the github link:

https://github.com/lpereira/lwan

"Website will not allow Firefox to display the page if another site has embedded it"

It would be nice that it was fixed, becasue is look like suspicious.

Sorry for the annoyances...

Thanks in advance...

**Comment by lpereira** [comment]
Thanks for letting me know! I tried fixing this but apparently it didn't work. Will have to find a way to do this without getting rid of the sandboxing features.
