### ISSUE TITLE
No such file or directory  lwan.h 166 | #include "lwan-http-status.h"

### ISSUE THREAD

**Issue by bumagh** [lpereira/lwan#361]
/usr/local/include/lwan/lwan.h:166:10: fatal error: lwan-http-status.h: No such file or directory   166 | #include "lwan-http-status.h"

**Comment by bumagh** [comment]
Ok, I solve this by do below
cp /root/work/netlibs/lwan/src/lib/lwan-http-status.h /usr/local/include/lwan/lwan-http-status.h

**Comment by lpereira** [comment]
Thanks! I forgot to add that header to the list of headers to be installed.
