### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [lpereira/lwan#59]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "close a stream") ⇒ [config_close](https://github.com/lpereira/lwan/blob/a3859a11750b5c67187c34e6888e4c2c45c6d6ce/common/lwan-config.c#L208)
- [fwrite](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fwrite.html "binary output") ⇒ [_status_out_msg](https://github.com/lpereira/lwan/blob/946ee7f44887c1be140cd531e400f241bcf92264/common/lwan-status.c#L95)
- [signal](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html "signal management") ⇒ [lwan_main_loop](https://github.com/lpereira/lwan/blob/e660ab753bfc83eb428c5b7de98bd40341589614/common/lwan.c#L555)

**Comment by lpereira** [comment]
All reported spots have been fixed. Thank you.

**Comment by elfring** [comment]
How do you think about to reconsider also return values from a call of a function like "[close](https://github.com/lpereira/lwan/blob/da15a8ca66dc5dc117d9f1a65d3d22e7b972305a/common/hash.c#L64 "Is initialize_odd_constant() another update candidate?")"?

**Comment by lpereira** [comment]
There's nothing to do under Linux, except reporting it. Even handling `EINTR` is incorrect under Linux (might introduce a race condition).

**Comment by elfring** [comment]
Would you like to detect every error situation as early as possible?

How do you think about to care also for return values from a function like "[pthread_mutex_(un)lock](https://github.com/lpereira/lwan/blob/75a35ef1abbf5ae369ca9db26d1ddaa44fe31fd7/common/lwan-job.c#L44 "Is job_thread() another update candidate?")"?
